dateModified: 1721261550
email:
  fromEmail: harshranpariya@gmail.com
  fromName: craft-cms
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5ff03b9c-2442-42c1-8f52-5f05805d8703: Default # Default
    8c2bcd86-15ca-4745-9541-62c2517f3fae: Card # Card
    8ea480cf-3da8-4bfc-a985-f534883b7508: CustomField # CustomField
    9a5c4aba-4556-4449-9a8d-0489adee3d51: Homepage # Homepage
    93a97e86-5fb7-448e-b123-41a810c115f2: Author # Author
    94bcec18-e515-40d9-8d7a-ed73b9849ce7: Simple # Simple
    6761c64d-369e-4597-b761-320df4750db6: 'Custom Field Section' # Custom Field Section
    025919fc-e603-489a-bfa2-46418536e529: craft-cms # craft-cms
    197137b7-f478-47f0-9c4b-ae27e535f80c: description # description
    694932c1-c350-45e9-a07f-55f670cf20b0: Homepage # Homepage
    ba543b48-0a3a-43cb-8f98-47018d64def7: Common # Common
    c19361e7-57b0-43c7-8f35-9cebc6c858c0: 'Default Card' # Default Card
    ccbc0ea7-9876-4b58-8dea-944edeeae7df: craft-cms # craft-cms
    d7a144d0-2bc9-4834-9f9a-c467fc34b5e3: richtext # richtext
    dbd589c9-d094-4942-b927-6b84e2b9bc3b: TitleHeading # TitleHeading
    defea8a7-02d5-4a34-851b-2ea0457a18c4: Default # Default
    e30f8fdb-65d7-4dbb-b94b-ba03b28d52d5: 'Public Schema' # Public Schema
    f2875265-3d8d-4786-b3f3-3f11b2a6ddf9: authorBio # authorBio
plugins:
  _test:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: solo
  live: true
  name: craft-cms
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
