defaultPlacement: end
enableVersioning: true
handle: author
name: Author
propagationMethod: all
siteSettings:
  ccbc0ea7-9876-4b58-8dea-944edeeae7df: # craft-cms
    enabledByDefault: true
    hasUrls: true
    template: author.twig
    uriFormat: 'author/{slug}'
type: channel
